name = "site"
type = "webpack"
account_id = "39dedd7c36e448f2b238733a98086e61"
workers_dev = false
route = "*tndl.me/*"
zone_id = "2519b8a0e65afba14e8234ed6da567be"

[site]
bucket = "./public"
entry-point = "workers-site"
